replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ''
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

resources: {}
commands: []
args: []

service:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: port-1
      nodePort: 32000

ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts: []
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: {}
affinity: {}
