replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ''
imagePullSecrets: []

resources: {}
commands: []
args: []

service:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: port-1

ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts: []
  tls: []

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: {}
affinity: {}
